site_name: IUEditor Manual (EN)
pages:
  - ['index.md', 'Home']
  - ['Introduction/what-is-the-iueditor.md', 'Introduction', 'What is IUEditor?']
  - ['Introduction/environment.md', 'Introduction', 'Environment']
  
  - ['Features/top-tool-bar.md', 'Basic Feature', 'Top Toolbar']
  - ['Features/middle-tool-bar.md', 'Basic Feature', 'Middel Toolbar']
  - ['Features/navigation.md', 'Basic Feature', 'Navigation']
  - ['Features/canvas.md', 'Basic Feature', 'Canvas']
  
  - ['Panel/resource-panel.md', 'Panel', 'Resource Panel']
  - ['Panel/event-panel.md', 'Panel', 'Event Panel']
  - ['Panel/memo-panel.md', 'Panel', 'Memo Panel']
  - ['Panel/custom-code-panel.md', 'Panel', 'Custom Code Panel']
  - ['Panel/import-widget-panel.md', 'Panel', 'Import Widget Panel']
  
  - ['Sheet/page.md', 'Sheet', 'Page']
  - ['Sheet/composition.md', 'Sheet', 'Composition']

  - ['Widget/basic.md', 'Widget', 'Basic Widget']
  - ['Widget/complex.md', 'Widget', 'Complex Widget']
  - ['Widget/programming.md', 'Widget', 'Programming Widget']
    
  - ['Knownbug/known-bug.md', 'Known Bugs', 'Known bugs']

  - ['Tutorial/tutorial.md', 'IUEditor Tutorial', 'IUEditor Tutorial']  
  
  - ['Appendix/appendix-templates.md', 'Appendix', 'Templates']  
  - ['Appendix/appendix-shortcut.md', 'Appendix', 'Shortcuts']  
  - ['Appendix/appendix-voca.md', 'Appendix', 'Dictionaries']
  


theme: readthedocs
site_author: "iu@jdlab.org"
repo_url: https://github.com/JDLabOrg/IUManual-EN.git

include_search : true
include_nav : true
include_next_prev : true
use_directory_urls : false
